version: '2'
services:
    api:
        build:
            context: .
        ports:
            - 8080:8080
        environment:
            - DATABASE_URL=postgres://postgres:password@postgres:5432/postgres
        links:
            - postgres
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=password
